"""DealLens AI — recruiter-ready Streamlit investigation workspace."""

import os
import sys
from pathlib import Path

# Allow imports from the project root
sys.path.insert(
    0,
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import networkx as nx

from backend.services import pipeline
from risk_engine.findings import to_markdown
from finance_engine.scenarios import (
    Base,
    Scenario,
    run as run_scenario,
    sensitivity,
)
from graph_engine.knowledge_graph import build_graph


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="DealLens AI",
    page_icon="🔎",
    layout="wide",
)


# ============================================================
# CONSTANTS / HELPERS
# ============================================================

SEV = {
    "High": "🔴",
    "Medium": "🟠",
    "Low": "🟡",
}


def cr(value):
    """Convert rupees to crore representation."""
    return f"₹{value / 1e7:,.1f} Cr"


def offline_investigation(question, state):
    """
    Evidence-backed fallback investigation assistant.

    This works without an API key and only uses
    deterministic findings already generated by DealLens.
    """

    q = question.lower()

    findings = state["findings"]
    selected = findings

    if any(
        x in q
        for x in ["customer", "revenue concentration", "churn"]
    ):
        selected = [
            x for x in findings
            if x["category"] == "Dependency"
            and "Customer" in x["title"]
        ]

    elif any(
        x in q
        for x in ["supplier", "procurement"]
    ):
        selected = [
            x for x in findings
            if "Supplier concentration" in x["title"]
        ]

    elif any(
        x in q
        for x in [
            "cash",
            "profit",
            "earnings",
            "receivable",
            "dso",
        ]
    ):
        selected = [
            x for x in findings
            if x["category"]
            in [
                "Earnings quality",
                "Revenue quality",
                "Working capital",
            ]
        ]

    elif any(
        x in q
        for x in [
            "transaction",
            "payment",
            "anomal",
            "threshold",
            "benford",
        ]
    ):
        selected = [
            x for x in findings
            if x["category"] == "Transactions"
        ]

    elif any(
        x in q
        for x in [
            "debt",
            "liquidity",
            "leverage",
        ]
    ):
        selected = [
            x for x in findings
            if x["category"]
            in [
                "Liquidity",
                "Leverage",
            ]
        ]

    elif any(
        x in q
        for x in [
            "contract",
            "renewal",
            "acquisition",
        ]
    ):
        selected = [
            x for x in findings
            if x["category"] == "Contract exposure"
        ]

    if not selected:
        selected = findings[:5]

    lines = [
        "### Evidence-backed investigation",
        f"**Question:** {question}",
        "",
    ]

    for finding in selected[:5]:

        lines += [
            (
                f"**{SEV.get(finding['severity'], '🟡')} "
                f"{finding['title']}**"
            ),
            finding["detail"],
            f"Evidence: `{finding['evidence']}`",
            (
                "Management questions: "
                + " ".join(
                    f"- {question}"
                    for question in finding["questions"]
                )
            ),
            "",
        ]

    lines.append(
        "_Offline mode uses deterministic project outputs; "
        "enable the optional LLM agent for natural-language "
        "multi-step investigation._"
    )

    return "\n".join(lines)


def graph_figure(state):
    """
    Create an interactive dependency graph
    using NetworkX + Plotly.
    """

    graph = build_graph(
        "Target Co",
        state["cust"],
        state["sup"],
        state["debt"],
        state["contracts"],
    )

    positions = nx.spring_layout(
        graph,
        seed=7,
        k=1.5,
    )

    edge_x = []
    edge_y = []

    for source, target in graph.edges():

        x0, y0 = positions[source]
        x1, y1 = positions[target]

        edge_x += [
            x0,
            x1,
            None,
        ]

        edge_y += [
            y0,
            y1,
            None,
        ]

    edge_trace = go.Scatter(
        x=edge_x,
        y=edge_y,
        mode="lines",
        line=dict(width=1),
        hoverinfo="none",
    )

    node_x = []
    node_y = []
    hover_text = []
    node_sizes = []

    for node, data in graph.nodes(data=True):

        x, y = positions[node]

        node_x.append(x)
        node_y.append(y)

        hover_text.append(
            f"{node}<br>"
            f"Type: {data.get('kind', 'entity')}"
        )

        node_sizes.append(
            28
            if data.get("kind") == "company"
            else 14
        )

    node_trace = go.Scatter(
        x=node_x,
        y=node_y,
        mode="markers+text",
        text=list(graph.nodes()),
        textposition="bottom center",
        hovertext=hover_text,
        hoverinfo="text",
        marker=dict(
            size=node_sizes,
            line=dict(width=1),
        ),
    )

    fig = go.Figure(
        [
            edge_trace,
            node_trace,
        ]
    )

    fig.update_layout(
        title="Target-company dependency graph",
        showlegend=False,
        margin=dict(
            l=10,
            r=10,
            t=50,
            b=10,
        ),
        xaxis=dict(
            showgrid=False,
            visible=False,
        ),
        yaxis=dict(
            showgrid=False,
            visible=False,
        ),
    )

    return fig


# ============================================================
# HEADER
# ============================================================

st.title("🔎 DealLens AI")

st.caption(
    "AI-powered M&A due-diligence & risk intelligence "
    "• evidence first • human analyst in the loop"
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("Investigation Workspace")

    st.write(
        "Upload source documents, then run the "
        "deterministic analysis pipeline."
    )

    files = st.file_uploader(
        "Source documents",
        type=[
            "pdf",
            "csv",
            "xlsx",
        ],
        accept_multiple_files=True,
        help=(
            "PDFs are indexed for page-cited search. "
            "CSV/XLSX files can replace matching files "
            "in data/raw."
        ),
    )

    if files:

        for uploaded_file in files:

            destination = (
                Path("data/raw")
                / Path(uploaded_file.name).name
            )

            destination.write_bytes(
                uploaded_file.getbuffer()
            )

            if destination.suffix.lower() == ".pdf":

                st.success(
                    f"Indexed {uploaded_file.name}: "
                    f"{pipeline.add_pdf(str(destination))} chunks"
                )

            else:

                st.success(
                    f"Loaded {uploaded_file.name}"
                )

    if st.button(
        "Run full analysis",
        type="primary",
        use_container_width=True,
    ):

        with st.spinner(
            "Running finance, anomaly, dependency "
            "and contract engines..."
        ):

            pipeline.analyze()

        st.success("Analysis complete.")

    st.divider()

    st.caption(
        "Numbers are calculated by Python. "
        "LLM interpretation is optional."
    )


# ============================================================
# PIPELINE STATE
# ============================================================

STATE = pipeline.STATE

if not STATE:

    st.info(
        "Click **Run full analysis** to analyze "
        "the included synthetic target company."
    )

    st.code(
        "python data/generate_sample_data.py\n"
        "streamlit run frontend/app.py",
        language="bash",
    )

    st.stop()


# ============================================================
# TOP KPI STRIP
# ============================================================

findings = STATE["findings"]

high = sum(
    finding["severity"] == "High"
    for finding in findings
)

medium = sum(
    finding["severity"] == "Medium"
    for finding in findings
)

latest = (
    STATE["ratios"]
    .sort_values("year")
    .iloc[-1]
)

top_customer = (
    STATE["cust"]
    .sort_values(
        "revenue",
        ascending=False,
    )
    .iloc[0]
)

top_supplier = (
    STATE["sup"]
    .sort_values(
        "procurement",
        ascending=False,
    )
    .iloc[0]
)


kpi_columns = st.columns(5)

kpi_columns[0].metric(
    "Risks requiring review",
    len(findings),
    f"{high} high",
)

kpi_columns[1].metric(
    "Revenue growth",
    f"{latest['revenue_growth']:.1%}",
)

kpi_columns[2].metric(
    "EBITDA margin",
    f"{latest['ebitda_margin']:.1%}",
)

kpi_columns[3].metric(
    "Top customer",
    (
        f"{top_customer['revenue'] / STATE['cust']['revenue'].sum():.0%}"
    ),
)

kpi_columns[4].metric(
    "Top supplier",
    (
        f"{top_supplier['procurement'] / STATE['sup']['procurement'].sum():.0%}"
    ),
)


# ============================================================
# MAIN TABS
# ============================================================

tabs = st.tabs(
    [
        "Executive View",
        "Risk Register",
        "Financials",
        "Dependencies",
        "Transactions",
        "Scenario",
        "Documents / AI",
    ]
)


# ============================================================
# EXECUTIVE VIEW
# ============================================================

with tabs[0]:

    st.subheader(
        "Executive investigation brief"
    )

    left, right = st.columns(
        [1.4, 1]
    )

    with left:

        st.markdown(
            "**Highest-priority themes**"
        )

        for finding in findings[:6]:

            st.markdown(
                f"{SEV[finding['severity']]} "
                f"**{finding['title']}**  \n"
                f"{finding['detail']}"
            )

    with right:

        severity_df = pd.DataFrame(
            {
                "Severity": [
                    "High",
                    "Medium",
                    "Low",
                ],
                "Count": [
                    sum(
                        x["severity"] == "High"
                        for x in findings
                    ),
                    sum(
                        x["severity"] == "Medium"
                        for x in findings
                    ),
                    sum(
                        x["severity"] == "Low"
                        for x in findings
                    ),
                ],
            }
        )

        st.plotly_chart(
            px.bar(
                severity_df,
                x="Severity",
                y="Count",
                title="Finding severity",
                text="Count",
            ),
            use_container_width=True,
        )

    st.info(
        "This is intentionally not a single opaque "
        "'deal score'. DealLens separates deterministic "
        "calculations, ML screening signals and "
        "investigation questions."
    )

    st.download_button(
        "⬇ Download due-diligence report",
        to_markdown(findings),
        "deallens_due_diligence.md",
        use_container_width=True,
    )


# ============================================================
# RISK REGISTER
# ============================================================

with tabs[1]:

    st.subheader("Risk register")

    for finding in findings:

        with st.expander(
            f"{SEV[finding['severity']]} "
            f"#{finding['rank']} • "
            f"{finding['title']}"
        ):

            left, right = st.columns(
                [1.6, 1]
            )

            with left:

                st.write(
                    finding["detail"]
                )

                st.markdown(
                    "**Evidence**"
                )

                st.json(
                    finding["evidence"]
                )

            with right:

                st.markdown(
                    "**Questions for management**"
                )

                for question in finding[
                    "questions"
                ]:

                    st.write(
                        "• " + question
                    )

    st.caption(
        f"{len(findings)} findings generated from "
        "financials, transactions, customer/supplier "
        "data, debt and contracts."
    )


# ============================================================
# FINANCIALS
# ============================================================

with tabs[2]:

    ratios = STATE["ratios"]

    st.subheader(
        "Deterministic financial analysis"
    )

    metric = st.selectbox(
        "Trend metric",
        [
            "revenue_growth",
            "ebitda_margin",
            "cash_conversion",
            "dso",
            "debt_to_ebitda",
            "interest_coverage",
        ],
    )

    st.plotly_chart(
        px.line(
            ratios,
            x="year",
            y=metric,
            markers=True,
            title=metric
            .replace("_", " ")
            .title(),
        ),
        use_container_width=True,
    )

    st.dataframe(
        ratios
        .set_index("year")
        .T
        .style
        .format("{:,.2f}"),
        use_container_width=True,
    )

    st.caption(
        "All ratios are calculated in Python "
        "rather than generated by the LLM."
    )


# ============================================================
# DEPENDENCIES
# ============================================================

with tabs[3]:

    st.subheader(
        "Customer & supplier dependency intelligence"
    )

    left, right = st.columns(2)

    with left:

        st.plotly_chart(
            px.pie(
                STATE["cust"],
                names="customer",
                values="revenue",
                hole=0.45,
                title="Revenue concentration",
            ),
            use_container_width=True,
        )

    with right:

        st.plotly_chart(
            px.pie(
                STATE["sup"],
                names="supplier",
                values="procurement",
                hole=0.45,
                title="Procurement concentration",
            ),
            use_container_width=True,
        )

    st.plotly_chart(
        graph_figure(STATE),
        use_container_width=True,
    )

    st.caption(
        "The graph connects the target to customers, "
        "suppliers, lenders and contracts; this supports "
        "cross-document reasoning."
    )


# ============================================================
# TRANSACTIONS
# ============================================================

with tabs[4]:

    st.subheader(
        "Transaction anomaly detective"
    )

    column_a, column_b, column_c = st.columns(3)

    column_a.metric(
        "Transactions screened",
        f"{len(STATE['scored_tx']):,}",
    )

    column_a.metric(
        "Isolation Forest outliers",
        f"{int(STATE['scored_tx']['is_outlier'].sum()):,}",
    )

    column_b.metric(
        "Benford χ²",
        f"{STATE['benford']['chi_square']:.1f}",
    )

    column_b.metric(
        "Benford screening flag",
        (
            "Review"
            if STATE["benford"]["suspicious"]
            else "No flag"
        ),
    )

    column_c.metric(
        "Top anomaly vendor",
        str(
            STATE["scored_tx"]
            .iloc[0]["vendor"]
        ),
    )

    column_c.metric(
        "Highest anomaly score",
        f"{STATE['scored_tx'].iloc[0]['anomaly_score']:.3f}",
    )

    top_transactions = (
        STATE["scored_tx"]
        .head(30)
        .copy()
    )

    st.plotly_chart(
        px.scatter(
            top_transactions,
            x="date",
            y="amount",
            size="anomaly_score",
            color="vendor",
            hover_data=[
                "anomaly_score"
            ],
            title=(
                "Highest-scoring transactions"
            ),
        ),
        use_container_width=True,
    )

    st.dataframe(
        top_transactions[
            [
                "date",
                "vendor",
                "amount",
                "anomaly_score",
                "is_outlier",
            ]
        ],
        use_container_width=True,
    )


# ============================================================
# SCENARIO SIMULATOR
# ============================================================

with tabs[5]:

    st.subheader(
        "M&A scenario simulator"
    )

    latest_financials = (
        STATE["fin"]
        .sort_values("year")
        .iloc[-1]
    )

    base = Base(
        latest_financials.revenue,
        latest_financials.cogs,
        latest_financials.operating_expenses,
        latest_financials.depreciation,
        latest_financials.interest_expense,
        latest_financials.capex,
        latest_financials.total_debt,
        latest_financials.interest_expense
        + STATE["debt"]["principal"].sum() * 0.2,
    )

    revenue_change = (
        st.slider(
            "Revenue change %",
            -40,
            40,
            -15,
        )
        / 100
    )

    operating_cost_change = (
        st.slider(
            "Operating cost change %",
            -20,
            30,
            8,
        )
        / 100
    )

    lost_customer_revenue = (
        st.slider(
            "Lost customer revenue (Cr)",
            0,
            100,
            0,
        )
        * 1e7
    )

    annual_synergy = (
        st.slider(
            "Annual synergy (Cr)",
            0,
            100,
            0,
        )
        * 1e7
    )

    output = run_scenario(
        base,
        Scenario(
            revenue_change=revenue_change,
            opex_change=operating_cost_change,
            lost_customer_revenue=lost_customer_revenue,
            synergy=annual_synergy,
        ),
    )

    metrics = st.columns(4)

    metrics[0].metric(
        "Revenue",
        cr(output["revenue"]),
        cr(output["delta_revenue"]),
    )

    metrics[1].metric(
        "EBITDA",
        cr(output["ebitda"]),
        cr(output["delta_ebitda"]),
    )

    metrics[2].metric(
        "Free cash flow",
        cr(output["free_cash_flow"]),
        cr(output["delta_fcf"]),
    )

    metrics[3].metric(
        "Debt / EBITDA",
        f"{output['debt_to_ebitda']:.2f}x",
    )

    sensitivity_df = pd.DataFrame(
        sensitivity(
            base,
            Scenario(
                revenue_change=revenue_change,
                opex_change=operating_cost_change,
                lost_customer_revenue=lost_customer_revenue,
                synergy=annual_synergy,
            ),
            "revenue_change",
            [
                x / 100
                for x in range(
                    -30,
                    31,
                    5,
                )
            ],
        )
    )

    st.plotly_chart(
        px.line(
            sensitivity_df,
            x="revenue_change",
            y="ebitda",
            markers=True,
            title=(
                "EBITDA sensitivity "
                "to revenue growth"
            ),
        ),
        use_container_width=True,
    )


# ============================================================
# DOCUMENTS / AI
# ============================================================

with tabs[6]:

    st.subheader(
        "Evidence search & investigation assistant"
    )

    document_query = st.text_input(
        "Search indexed documents",
        placeholder=(
            "e.g. change of control, "
            "renewal, debt maturity"
        ),
    )

    if document_query:

        if pipeline.DOCS["index"]:

            hits = pipeline.DOCS[
                "index"
            ].search(document_query)

            if hits:

                for hit in hits:

                    with st.expander(
                        f"{hit['source']} • "
                        f"page {hit['page']} • "
                        f"relevance {hit['score']:.2f}"
                    ):

                        st.write(
                            hit["text"]
                        )

            else:

                st.warning(
                    "No matching evidence found."
                )

        else:

            st.info(
                "Upload a PDF first to enable "
                "page-cited document search."
            )

    st.divider()

    question = st.text_input(
        "Investigation question",
        "Find the top financial risks an acquirer should investigate.",
    )

    if st.button(
        "Investigate",
        type="primary",
    ):

        if os.getenv(
            "ANTHROPIC_API_KEY"
        ):

            from agent.agent import investigate
            from agent.tools import Toolbox

            st.markdown(
                investigate(
                    question,
                    Toolbox(
                        STATE,
                        pipeline.DOCS["index"],
                    ),
                )
            )

        else:

            st.markdown(
                offline_investigation(
                    question,
                    STATE,
                )
            )

            st.caption(
                "Tip: add ANTHROPIC_API_KEY later "
                "to activate the multi-step "
                "tool-calling agent."
            )